name: Auto Version
on:
  push:
    branches:
      - main

jobs:
  get-version:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    uses: HalloftheGods/.github/.github/workflows/calculate-version.yml@main
    
  update-theme:
    needs: get-version
    uses: HalloftheGods/.github/.github/workflows/wp-theme-update.yml@main
    with:
      version_string: ${{ needs.get-version.outputs.version_string }}

  build-theme-zip:
    needs: [get-version, update-theme]
    uses: HalloftheGods/.github/.github/workflows/build-theme-zip.yml@main
    with:
      theme_slug: ${{ github.event.repository.name }}
      version: ${{ needs.get-version.outputs.version_string }}
